version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
      
  broker1:
    image: confluentinc/cp-kafka
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://112.124.53.234:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  broker2:
    image: confluentinc/cp-kafka
    container_name: broker2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://112.124.53.234:9093
    restart: always
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatgpt-web
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined  
  redis:
    image: redis:6.2.3
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx/nginx_produce.conf:/etc/nginx/nginx.conf
      - ./server.crt:/usr/server.crt
      - ./server.key:/usr/server.key
  web:
    build: ./server/fontend.dockerfile
    ports:
      - "3000:3000"


volumes:
  mysql_data:
  redis_data: 
